version: "3.3"

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:15
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
